version: '3'

networks:
  laravel:


services:
  app:
    build:
      context: ./dockerfiles/nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - laravel
  php:
    build:
      context: ./dockerfiles/php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
